plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/adamfrancis/Documents/EduProject/CascadeProjects/windsurf-project/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]